<a href="https://colab.research.google.com/github/Kavya2905/Building-a-NeuralNetwork/blob/main/Building_a_Simple_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Importing libraries

import numpy as np

In [ ]:
x = np.array([[0,1,0],[0,1,1],[1,0,0],[1,0,1]])
y = np.array([[0],[0],[1],[1]])

In [ ]:
x

array([[0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1]])

In [ ]:
y

array([[0],
       [0],
       [1],
       [1]])

In [ ]:
# Assign the weights (Random)

np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [ ]:
sum = np.dot(x,weights) + 0.02
sum

array([[0.04075195],
       [0.67440018],
       [0.79132064],
       [1.42496888]])

In [ ]:
### Activation function

def activation(x):
  return 1/(1+np.exp(-x))

In [ ]:
### Predicting values

ypred = activation(sum)
ypred

array([[0.51018658],
       [0.66248773],
       [0.68811483],
       [0.8061162 ]])

In [ ]:
ypred.round()                                     ## To round off

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
### Gradient descent

def gradient(a,x):
  return a* x * (1-x)                            ## x(1-x) = derivative of sigmoid

In [ ]:
sum = np.dot(x,weights) + 0.02
ypred = activation(sum)
error = y-ypred
change_weight = gradient(error,  ypred)          ## Gradient descent
weights = weights + np.dot(x.T, change_weight)
error

array([[-0.01617692],
       [-0.01626926],
       [ 0.01630667],
       [ 0.01621413]])

In [ ]:
for i in range(500):
  sum = np.dot(x,weights) + 0.02
  ypred = activation(sum)
  error = y-ypred
  change_weight = gradient(error,  ypred)
  weights = weights + np.dot(x.T, change_weight)


In [ ]:
error

array([[-0.02309041],
       [-0.02325249],
       [ 0.0233153 ],
       [ 0.02315279]])

In [ ]:
ypred

array([[0.02309041],
       [0.02325249],
       [0.9766847 ],
       [0.97684721]])

In [ ]:
ypred.round()

array([[0.],
       [0.],
       [1.],
       [1.]])

In [ ]:
weights

array([[ 3.71610869],
       [-3.76602564],
       [ 0.00715645]])